### ISSUE TITLE
Add query parameters support

### ISSUE THREAD

**Issue by greenstatic** [greenstatic/RCE#8]
Add the posibility to add optional or required query parameters to an endpoint. Here is an example of what it could look like:

**config.yaml**
```yaml
base-endpoint: "command"
index-enable: true
scripts:
  - endpoint: "myage" 
    http-methods:
      - "GET" 
    response-stdout: true
    response-stderr: true
    query-params:
      - query: "age"
        type: "int"
        required: true
      - query: "unit"
        type: "string"
        required: true

    command: "echo"
        args: 
          - "I am"
          - "#age"
          - "#unit"
          - "old."
```

**Endpoint execution**
```bash
$ curl -X GET http://localhost:2233/command/myage?age=12&unit=years

{
    "stdout": "I am 12 years old\n",
    "stderr": "",
    "successful": true
}
```

Under the command arguments of the config a hashtag (\#) could represent the query variable (if it is set). It would be useful to implement a basic type check (string, int, bool). 

If the feature is going to be implemented we need to be very careful about escaping the query parameters to prevent arbitrary code execution.
