### ISSUE TITLE
Add API key support

### ISSUE THREAD

**Issue by greenstatic** [greenstatic/RCE#9]
It would be useful if besides HTTP Basic Authentication we would have a dedicated query parameter (such as api_key) used for authentication.

**config.yaml**
```yaml
base-endpoint: "command"
index-enable: true
commands:
  - endpoint: "hello" 
    http-methods:
      - "GET" 
    response-stdout: true
    response-stderr: true
    api-key:
      - "secret-foo"
      - "second-secret-foo"
    command: "echo"
    args: 
      - "Hello"
```

**Endpoint execution**
```bash
$ curl -X GET http://localhost:2233/command/hello?api_key=secret-foo

{
    "stdout": "Hello\n",
    "stderr": "",
    "successful": true
}

$ curl -X GET http://localhost:2233/command/hello
# HTTP code: 401
{
    "successful": false
}
```
